#!/usr/bin/env python3
"""Generates docs/cbom-source-map.md and docs/RESULTS.md from the scanner output in out/.

Everything here is derived from the JSON the scanners actually produced, so re-running the scans
and re-running this script keeps the documents honest. Nothing is hand-transcribed.
"""
from __future__ import annotations

import collections
import json
import pathlib
import re
import subprocess
import datetime

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "out"
DOCS = ROOT / "docs"

SCANNERS = {
    "sonar": ("PQCA sonar-cryptography", "AST + type resolution", "out/cbom-sonar.json"),
    "cdxgen": ("cdxgen --include-crypto", "keyword to OID mapping", "out/cbom-cdxgen.json"),
    "theia": ("cbomkit-theia (working tree)", "filesystem inspection", "out/cbom-theia.json"),
    "image": ("cbomkit-theia (image)", "container filesystem", "out/cbom-image.json"),
    "sbom-image": ("cdxgen (container)", "OS package inventory", "out/sbom-image.json"),
}


def load(name: str):
    path = ROOT / SCANNERS[name][2]
    if not path.exists():
        return None
    return json.loads(path.read_text())


def assets(bom) -> list:
    if not bom:
        return []
    return [c for c in bom.get("components") or [] if c.get("type") == "cryptographic-asset"]


def alg_props(asset) -> dict:
    return asset.get("cryptoProperties", {}).get("algorithmProperties", {}) or {}


def source_line(path: str, line: int) -> str:
    """The actual line of Java the scanner pointed at, trimmed for a table cell."""
    file = ROOT / path
    if not file.exists() or not line:
        return ""
    try:
        text = file.read_text().splitlines()[line - 1].strip()
    except IndexError:
        return ""
    return re.sub(r"\s+", " ", text).replace("|", "\\|")


def occurrences(asset) -> list[tuple[str, int]]:
    out = []
    for o in asset.get("evidence", {}).get("occurrences", []) or []:
        out.append((o.get("location") or "", o.get("line") or 0))
    return sorted(set(out))


# --------------------------------------------------------------------------- source map
def write_source_map() -> None:
    bom = load("sonar")
    if not bom:
        raise SystemExit("out/cbom-sonar.json is missing; run ./scripts/scan-cbom.sh first")

    all_assets = assets(bom)
    by_type: dict[str, list] = collections.defaultdict(list)
    for a in all_assets:
        by_type[a["cryptoProperties"]["assetType"]].append(a)

    lines: list[str] = []
    add = lines.append
    add("# CBOM asset to source map")
    add("")
    add("Every cryptographic asset in `out/cbom-sonar.json`, traced back to the line of Java that")
    add("produced it. Generated by `scripts/report.py` from the scanner's own")
    add("`evidence.occurrences`, so it cannot drift from the CBOM it describes.")
    add("")
    add(f"{len(all_assets)} assets, "
        + ", ".join(f"{len(v)} {k}" for k, v in sorted(by_type.items()))
        + ".")
    add("")
    add("## How to read this")
    add("")
    add("An asset appears once no matter how many call sites produced it. The plugin keys components")
    add("by **name alone** and keeps the first one it builds, merging only `evidence.occurrences` into")
    add("it — so a row with several source locations shows the mode, padding and crypto functions of")
    add("whichever file was analysed first, and the rest were discarded. That is also why a bare `TLS`")
    add("asset can absorb a more detailed one, and why the analysis order matters: see `FINDINGS.md` §6.")
    add("")

    # --- algorithms, the interesting table
    add("## Algorithm assets")
    add("")
    add("| Asset | Primitive | Mode / parameters | Crypto functions | OID | Source |")
    add("| --- | --- | --- | --- | --- | --- |")
    for a in sorted(by_type.get("algorithm", []), key=lambda x: x["name"].lower()):
        p = alg_props(a)
        params = " ".join(filter(None, [
            p.get("mode", ""),
            p.get("padding", ""),
            f"n={p['parameterSetIdentifier']}" if p.get("parameterSetIdentifier") else "",
            p.get("curve", ""),
        ])) or "-"
        funcs = ", ".join(p.get("cryptoFunctions") or []) or "-"
        oid = a["cryptoProperties"].get("oid") or "-"
        src = "<br>".join(f"[{pathlib.Path(loc).name}:{ln}]({loc}#L{ln})"
                          for loc, ln in occurrences(a)) or "-"
        add(f"| `{a['name']}` | {p.get('primitive', '-')} | {params} | {funcs} | `{oid}` | {src} |")
    add("")

    # --- protocols
    add("## Protocol assets")
    add("")
    add("| Asset | Type | Version | Cipher suites | Source | Call |")
    add("| --- | --- | --- | --- | --- | --- |")
    for a in sorted(by_type.get("protocol", []), key=lambda x: x["name"]):
        pp = a["cryptoProperties"].get("protocolProperties", {}) or {}
        suites = pp.get("cipherSuites") or []
        occ = occurrences(a)
        src = "<br>".join(f"[{pathlib.Path(loc).name}:{ln}]({loc}#L{ln})" for loc, ln in occ) or "-"
        call = "<br>".join(f"`{source_line(loc, ln)}`" for loc, ln in occ) or "-"
        add(f"| `{a['name']}` | {pp.get('type', '-')} | {pp.get('version', '-')} "
            f"| {len(suites)} | {src} | {call} |")
    add("")

    # --- key material, grouped because 122 rows of "secret-key" teaches nothing
    add("## Related crypto material")
    add("")
    add("Key material, salts, IVs and passwords the scanner recovered from constructor arguments")
    add("and key-spec literals. Grouped by kind and size, since individual entries are anonymous.")
    add("")
    add("| Kind | Size | Count | Source files |")
    add("| --- | --- | --- | --- |")
    groups: dict[tuple[str, object], list] = collections.defaultdict(list)
    for a in by_type.get("related-crypto-material", []):
        rp = a["cryptoProperties"].get("relatedCryptoMaterialProperties", {}) or {}
        groups[(rp.get("type", "?"), rp.get("size", "-"))].append(a)
    for (kind, size), items in sorted(groups.items(), key=lambda kv: (kv[0][0], str(kv[0][1]))):
        files = sorted({pathlib.Path(loc).name for a in items for loc, _ in occurrences(a)})
        add(f"| {kind} | {size} | {len(items)} | {', '.join(files)} |")
    add("")

    # --- per-source-file roll-up: the view an article wants
    add("## Per source file")
    add("")
    add("Which demo class produced which assets. A file with zero assets is a finding, not an")
    add("omission — see `RESULTS.md`.")
    add("")
    add("| Source file | Assets | Named assets |")
    add("| --- | --- | --- |")
    per_file: dict[str, set] = collections.defaultdict(set)
    for a in all_assets:
        for loc, _ in occurrences(a):
            per_file[loc].add(a["name"])
    java_files = sorted(p.relative_to(ROOT).as_posix()
                        for p in (ROOT / "src/main/java").rglob("*.java"))
    for f in java_files:
        names = sorted(per_file.get(f, set()))
        shown = ", ".join(f"`{n}`" for n in names[:12])
        if len(names) > 12:
            shown += f", … (+{len(names) - 12})"
        add(f"| [{pathlib.Path(f).name}]({f}) | {len(names)} | {shown or '*none*'} |")
    add("")

    (DOCS / "cbom-source-map.md").write_text("\n".join(lines) + "\n")
    print(f"wrote docs/cbom-source-map.md ({len(all_assets)} assets)")


# --------------------------------------------------------------------------- results log
def tool_versions() -> dict[str, str]:
    def run(cmd: list[str]) -> str:
        """First line of output. java -version writes to stderr, so both streams are merged."""
        try:
            r = subprocess.run(cmd, capture_output=True, text=True, timeout=60, cwd=ROOT)
            return (r.stdout + r.stderr).strip().splitlines()[0]
        except Exception:
            return "not recorded"

    plugin = next((p.name for p in (ROOT / ".sonarqube/plugins").glob("*.jar")), "not installed")
    sonarqube = ""
    compose = (ROOT / "docker-compose.yml").read_text()
    m = re.search(r"image:\s*(sonarqube:[^\s]+)", compose)
    if m:
        sonarqube = m.group(1)
    cdxgen = ""
    # Logs live in out/work/; the BOM's own metadata is the fallback.
    log = OUT / "work" / "cdxgen.log"
    if log.exists():
        m = re.search(r"cdxgen@([0-9.]+)", log.read_text())
        if m:
            cdxgen = m.group(1)
    if not cdxgen:
        bom = load("cdxgen")
        if bom:
            comps = (bom.get("metadata", {}).get("tools", {}) or {}).get("components", []) or []
            cdxgen = next((c.get("version", "") for c in comps if c.get("name") == "cdxgen"), "")
    return {
        "sonar-cryptography plugin": plugin,
        "SonarQube": sonarqube or "not recorded",
        "cdxgen": cdxgen or "not recorded",
        "cbomkit-theia": "built from main (see scripts/scan-theia.sh)",
        "JDK": run(["java", "-version"]) or run(["java", "--version"]),
        "Maven": run(["mvn", "-v"]),
        "Docker": run(["docker", "--version"]),
    }


def write_results() -> None:
    rows = []
    for key in ("sonar", "cdxgen", "theia", "image"):
        bom = load(key)
        a = assets(bom)
        if not a:
            rows.append((SCANNERS[key][0], SCANNERS[key][1], None))
            continue
        types = collections.Counter(x["cryptoProperties"]["assetType"] for x in a)
        rows.append((SCANNERS[key][0], SCANNERS[key][1], {
            "total": len(a),
            "types": types,
            "oid": sum(1 for x in a if x["cryptoProperties"].get("oid")),
            "occ": sum(1 for x in a if x.get("evidence", {}).get("occurrences")),
            "mode": sum(1 for x in a if alg_props(x).get("mode")),
            "fn": sum(1 for x in a if alg_props(x).get("cryptoFunctions")),
            "qsl": sum(1 for x in a if alg_props(x).get("nistQuantumSecurityLevel")),
        }))

    # runtime evidence
    ev = ROOT / "target/runtime-evidence.md"
    ran = failed = 0
    if ev.exists():
        for line in ev.read_text().splitlines():
            if line.startswith("| `"):
                failed += 1 if "~~" in line else 0
                ran += 0 if "~~" in line else 1

    # container packages
    img = load("sbom-image")
    pkgs = []
    if img:
        pattern = re.compile(
            r"openssl|libssl|libcrypto|gnutls|nettle|gcrypt|k5crypto|p11-kit|ca-certificates")
        seen = {}
        for c in img.get("components", []):
            if c.get("type") == "library" and pattern.search(c["name"].lower()):
                seen.setdefault(c["name"], c.get("version", "?"))
        pkgs = sorted(seen.items())

    lines: list[str] = []
    add = lines.append
    add("# Recorded results")
    add("")
    add(f"Generated by `scripts/report.py` on {datetime.date.today().isoformat()} from the files in")
    add("`out/`. Re-run the scans and this script to refresh; do not edit the numbers by hand.")
    add("")
    add("Analysis of what these numbers mean, and the experiments behind them, is in")
    add("[FINDINGS.md](FINDINGS.md) — that file is written by hand and never overwritten here.")
    add("")
    add("## Environment")
    add("")
    add("| Component | Version |")
    add("| --- | --- |")
    for k, v in tool_versions().items():
        add(f"| {k} | {v} |")
    add("")
    add("## Scanner comparison")
    add("")
    add("| Scanner | Method | Assets | With OID | With source | With mode | With functions | With quantum level |")
    add("| --- | --- | --- | --- | --- | --- | --- | --- |")
    for name, method, s in rows:
        if s is None:
            add(f"| {name} | {method} | *not run* | | | | | |")
            continue
        add(f"| {name} | {method} | **{s['total']}** | {s['oid']} | {s['occ']} "
            f"| {s['mode']} | {s['fn']} | {s['qsl']} |")
    add("")
    add("### Asset types")
    add("")
    add("| Scanner | Breakdown |")
    add("| --- | --- |")
    for name, _, s in rows:
        if s is None:
            continue
        add(f"| {name} | " + ", ".join(f"{k}={v}" for k, v in sorted(s['types'].items())) + " |")
    add("")
    add("## Runtime execution")
    add("")
    add(f"`CbomDemoRunner` executed **{ran}** algorithm usages successfully; **{failed}** were")
    add("refused by the JVM. Full log with the serving provider per algorithm:")
    add("`target/runtime-evidence.md`.")
    add("")
    if pkgs:
        add("## Container crypto packages")
        add("")
        add("Crypto-providing operating-system packages found in the image by cdxgen. These are")
        add("`library` components, **not** cryptographic assets — openssl provides crypto, it is")
        add("not an instance of it.")
        add("")
        add("| Package | Version |")
        add("| --- | --- |")
        for name, version in pkgs:
            add(f"| `{name}` | {version} |")
        add("")
    (DOCS / "RESULTS.md").write_text("\n".join(lines) + "\n")
    print("wrote docs/RESULTS.md")


if __name__ == "__main__":
    DOCS.mkdir(exist_ok=True)
    write_source_map()
    write_results()
