package com.tinnapat.demo.cbom;

import java.nio.file.Files;
import java.nio.file.Path;
import java.security.Security;
import java.util.List;

import org.bouncycastle.jce.provider.BouncyCastleProvider;

import com.tinnapat.demo.cbom.bc.BcAeadCipherDemo;
import com.tinnapat.demo.cbom.bc.BcBlockCipherDemo;
import com.tinnapat.demo.cbom.bc.BcDigestDemo;
import com.tinnapat.demo.cbom.bc.BcKdfDemo;
import com.tinnapat.demo.cbom.bc.BcKeyAgreementDemo;
import com.tinnapat.demo.cbom.bc.BcMacDemo;
import com.tinnapat.demo.cbom.bc.BcPostQuantumDemo;
import com.tinnapat.demo.cbom.bc.BcSignerDemo;
import com.tinnapat.demo.cbom.gaps.ScannerGapDemo;
import com.tinnapat.demo.cbom.jca.JcaCipherDemo;
import com.tinnapat.demo.cbom.jca.JcaDigestDemo;
import com.tinnapat.demo.cbom.jca.JcaKeyAgreementDemo;
import com.tinnapat.demo.cbom.jca.JcaKeyDerivationDemo;
import com.tinnapat.demo.cbom.jca.JcaKeyGenerationDemo;
import com.tinnapat.demo.cbom.jca.JcaMacDemo;
import com.tinnapat.demo.cbom.jca.JcaRandomDemo;
import com.tinnapat.demo.cbom.jca.JcaSignatureDemo;
import com.tinnapat.demo.cbom.tls.TlsConfigurationDemo;

/**
 * Runs every demo group and writes a runtime evidence report to {@code target/runtime-evidence.md}.
 *
 * <p>A static CBOM says what the code can do; this report says what the JVM actually did, and with
 * which provider. Reading the two side by side is how you tell a scanner's blind spot apart from a
 * runtime restriction.
 */
public final class CbomDemoRunner {

	private static final Path OUTPUT_DIRECTORY = Path.of("target");

	public static void main(String[] args) throws Exception {
		if (Security.getProvider(BouncyCastleProvider.PROVIDER_NAME) == null) {
			Security.addProvider(new BouncyCastleProvider());
		}

		List<CryptoDemo> demos = List.of(
				new JcaCipherDemo(),
				new JcaDigestDemo(),
				new JcaMacDemo(),
				new JcaSignatureDemo(),
				new JcaKeyAgreementDemo(),
				new JcaKeyDerivationDemo(),
				new JcaKeyGenerationDemo(),
				new JcaRandomDemo(),
				new TlsConfigurationDemo(),
				new BcAeadCipherDemo(),
				new BcBlockCipherDemo(),
				new BcDigestDemo(),
				new BcMacDemo(),
				new BcSignerDemo(),
				new BcKdfDemo(),
				new BcKeyAgreementDemo(),
				new BcPostQuantumDemo(),
				new ScannerGapDemo(OUTPUT_DIRECTORY.resolve("demo-pki")));

		Evidence evidence = new Evidence();
		int failed = 0;
		for (CryptoDemo demo : demos) {
			evidence.group(demo.ruleGroup());
			try {
				demo.run(evidence);
				System.out.printf("%-52s ok%n", demo.getClass().getSimpleName());
			}
			catch (Exception ex) {
				failed++;
				System.out.printf("%-52s FAILED: %s: %s%n", demo.getClass().getSimpleName(),
						ex.getClass().getSimpleName(), ex.getMessage());
			}
		}

		Path report = OUTPUT_DIRECTORY.resolve("runtime-evidence.md");
		Files.createDirectories(OUTPUT_DIRECTORY);
		Files.writeString(report, render(evidence));

		System.out.printf("%n%d demo groups, %d algorithm usages executed, %d groups failed%n",
				demos.size(), evidence.executedCount(), failed);
		System.out.println("runtime evidence: " + report);
		if (failed > 0) {
			System.exit(1);
		}
	}

	private static String render(Evidence evidence) {
		StringBuilder out = new StringBuilder();
		out.append("# Runtime crypto evidence\n\n")
				.append("Generated by `CbomDemoRunner`. Each row is an algorithm the JVM actually ran, ")
				.append("with the provider that served it. Compare against `out/cbom-sonar.json`.\n\n")
				.append("| Rule group | Algorithm | Provider | Detail |\n")
				.append("| --- | --- | --- | --- |\n");
		for (Evidence.Entry entry : evidence.entries()) {
			out.append("| `").append(entry.ruleGroup()).append("` | ")
					.append(entry.executed() ? "" : "~~").append(entry.algorithm())
					.append(entry.executed() ? "" : "~~").append(" | ")
					.append(entry.provider()).append(" | ")
					.append(entry.detail()).append(" |\n");
		}
		out.append("\n").append(evidence.executedCount()).append(" of ").append(evidence.entries().size())
				.append(" usages executed successfully.\n");
		return out.toString();
	}
}
